# Generated by Django 4.0.1 on 2022-01-26 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0002_remove_task_description_remove_task_title_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['-created']},
        ),
        migrations.AlterField(
            model_name='task',
            name='-created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created Time'),
        ),
    ]
